from pydantic import BaseModel, Field
from typing import Literal


# ---------------------------------------------------------
# Menu Engineering Categories
#
# STAR        -> high margin + high popularity
# PUZZLE      -> high margin + low popularity
# PLOW_HORSE  -> low margin + high popularity
# LOW_END     -> low margin + low popularity
#
# These are NOT decisions.
# They are economic states.
# ---------------------------------------------------------

MatrixCategory = Literal["star", "puzzle", "plow_horse", "low_end"]


class MatrixItem(BaseModel):
    """
    Represents the raw economic state of a single menu item.

    IMPORTANT:
    This model should remain PURE.

    It describes reality — not interpretation.

    Future layers will derive:
        - primitives
        - roles
        - signals
        - promotion decisions

    Treat this as financial infrastructure.
    """

    # -----------------------------------------------------
    # Identity
    # -----------------------------------------------------

    menu: str = Field(description="Display name of the menu item.")

    menu_category: str = Field(
        description="Top-level category (e.g., DRINK, FOOD, DESSERT). Useful for marketing segmentation."
    )

    menu_category_detail: str = Field(
        description="More granular classification (e.g., ESPRESSO DRINKS, BURGERS). Enables smarter promotions later."
    )

    category: MatrixCategory = Field(
        description="Menu engineering quadrant representing the item's economic position."
    )

    action: Literal["keep", "reprice", "promote", "remove"] = Field(
        description="""
        Recommended action from the matrix calculation.

        NOTE:
        This is NOT an AI decision.
        It is a classical menu engineering output.
        Treat as advisory input — not deterministic truth.
        """
    )

    # -----------------------------------------------------
    # Sales Performance
    # -----------------------------------------------------

    quantity: int = Field(
        ge=0, description="Total units sold within the reporting period."
    )

    total_revenue: float = Field(
        ge=0, description="Gross revenue generated by this item."
    )

    # -----------------------------------------------------
    # Cost Structure
    # -----------------------------------------------------

    cogs: float = Field(ge=0, description="Cost of goods sold per unit.")

    total_cogs: float = Field(ge=0, description="Total cost incurred for this item.")

    # -----------------------------------------------------
    # Profitability
    # -----------------------------------------------------

    margin_per_unit: float = Field(
        description="""
        Profit earned per sale.

        One of the MOST important economic signals in hospitality.
        """
    )

    contribution_margin: float = Field(
        description="Total profit generated by this item."
    )

    contribution_margin_percentage: float = Field(
        ge=0,
        le=1,
        description="""
        Share of total restaurant profit attributable to this item.

        > 10% often indicates a profit anchor.
        """,
    )

    # -----------------------------------------------------
    # Matrix Coordinates
    # -----------------------------------------------------

    we_value: float = Field(
        description="""
        Weighted effectiveness score from menu engineering.

        Typically combines popularity + profitability.

        Useful for visualization — rarely used directly by agents.
        """
    )
