[project]
name = "graphql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.46",
    "strawberry-graphql[asgi]>=0.308.2",
    "uvicorn>=0.40.0",
    "psycopg2-binary>=2.9.5,<3.0",
    "python-dotenv>=1.2.1",
    "openpyxl>=3.1.2",
    "pytest>=9.0.0",
    "menuyukti",
]

[build-system]
requires = ["setuptools>=70.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "graphql",
    "graphql.schema",
    "graphql.resolvers",
    "graphql.data_sources",
    "graphql.reports",
]

[tool.setuptools.package-dir]
"graphql" = "."
"graphql.schema" = "schema"
"graphql.resolvers" = "resolvers"
"graphql.data_sources" = "data_sources"
"graphql.reports" = "reports"
