/**
 * Scenario-based database seeder (v2)
 *
 * Seeds the database with realistic restaurant data from menuyukti package scenarios.
 * Data is generated by Python scripts and uses real analytics calculations.
 *
 * Usage:
 *   pnpm db:seed:v2                    # Interactive menu
 *   pnpm db:seed:v2 thriving-cafe      # Specific scenario
 *   pnpm db:seed:v2 --all              # All scenarios
 *   pnpm db:seed:v2 --list             # List available scenarios
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { prisma } from "@/lib/prisma/client";

type ScenarioJsonData = {
  scenario: string;
  description: string;
  order_menu_items: Array<{
    bill_number: string;
    menu: string;
    qty: number;
    price: number;
    total_after_bill_discount: number;
    order_time: string;
    menu_category: string;
    menu_category_detail: string;
  }>;
  analytics_menu_items: Array<{
    menu_name: string;
    menu_category: string;
    menu_category_detail: string;
    quantity: number;
    total_revenue: number;
    cogs: number;
  }>;
};

type ScenarioConfig = {
  id: string;
  name: string;
  description: string;
  jsonFile: string;
  location: {
    name: string;
    slug: string;
  };
  analytics: {
    sourceFile: string;
    periodStart: Date;
    periodEnd: Date;
  };
};

const SCENARIOS: Record<string, ScenarioConfig> = {
  "thriving-cafe": {
    id: "thriving-cafe",
    name: "Thriving Downtown Cafe",
    description: "High-performing cafe with good margins and diverse menu",
    jsonFile: "thriving_cafe.json",
    location: {
      name: "Downtown Cafe",
      slug: "downtown-cafe",
    },
    analytics: {
      sourceFile: "sales_report_q1_2025.xlsx",
      periodStart: new Date("2025-01-01"),
      periodEnd: new Date("2025-03-31"),
    },
  },
  "struggling-restaurant": {
    id: "struggling-restaurant",
    name: "Struggling Family Restaurant",
    description: "Restaurant with low margins and underperforming items",
    jsonFile: "struggling_restaurant.json",
    location: {
      name: "Family Kitchen",
      slug: "family-kitchen",
    },
    analytics: {
      sourceFile: "sales_report_q1_2025.xlsx",
      periodStart: new Date("2025-01-01"),
      periodEnd: new Date("2025-03-31"),
    },
  },
  "star-item": {
    id: "star-item",
    name: "Star Item Restaurant",
    description: "Restaurant with one dominant high-margin item",
    jsonFile: "star_item.json",
    location: {
      name: "Star Bowl",
      slug: "star-bowl",
    },
    analytics: {
      sourceFile: "sales_report_jan_2026.xlsx",
      periodStart: new Date("2026-01-15"),
      periodEnd: new Date("2026-01-19"),
    },
  },
};

async function loadScenarioData(jsonFile: string): Promise<ScenarioJsonData> {
  const scenarioPath = join(
    process.cwd(),
    "..",
    "..",
    "packages",
    "menuyukti",
    "seed_scenarios",
    jsonFile,
  );
  const content = await readFile(scenarioPath, "utf-8");
  return JSON.parse(content);
}

async function callAnalyticsApi(payload: {
  items: Array<{
    menu_name: string;
    quantity: number;
    total_revenue: number;
    cogs: number;
    menu_category?: string;
  }>;
}) {
  const analyticsUrl = process.env.ANALYTICS_API_URL || "http://localhost:8000";

  console.log(`   ⏳ Calling analytics API at ${analyticsUrl}...`);

  // Call matrix endpoint
  const matrixResponse = await fetch(`${analyticsUrl}/menu-items/matrix`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!matrixResponse.ok) {
    const error = await matrixResponse.text();
    throw new Error(`Matrix API failed: ${matrixResponse.status} - ${error}`);
  }

  const matrixResult = await matrixResponse.json();

  console.log(`   ✓ Analytics calculations complete`);

  // Extract the matrix data
  return {
    heatmapJson: [], // TODO: heatmap requires time-series data, not just aggregates
    popularityJson: null,
    matrixJson: matrixResult.matrix || null,
    matrixDistributionJson: matrixResult.matrix?.distribution || null,
  };
}

async function seedScenario(config: ScenarioConfig): Promise<void> {
  console.log(`\n📦 Seeding: ${config.name}`);
  console.log(`   ${config.description}`);

  // 1. Load scenario data from JSON
  console.log(`   📄 Loading ${config.jsonFile}...`);
  const data = await loadScenarioData(config.jsonFile);
  const menuItems = data.analytics_menu_items;

  // 2. Create or find location
  let location = await prisma.location.findUnique({
    where: { slug: config.location.slug },
  });

  if (!location) {
    location = await prisma.location.create({
      data: {
        name: config.location.name,
        slug: config.location.slug,
      },
    });
    console.log(`   ✓ Created location: ${location.name}`);
  } else {
    console.log(`   ✓ Using existing location: ${location.name}`);
  }

  // 3. Calculate aggregated metrics
  const totalItemsSold = menuItems.reduce(
    (sum, item) => sum + item.quantity,
    0,
  );
  const totalRevenue = menuItems.reduce(
    (sum, item) => sum + item.total_revenue,
    0,
  );
  const totalCogs = menuItems.reduce((sum, item) => sum + item.cogs, 0);
  const totalProfit = totalRevenue - totalCogs;
  const totalMargin = totalRevenue > 0 ? totalProfit / totalRevenue : 0;
  const totalOrders = Math.ceil(totalItemsSold / 2.5); // Avg 2.5 items per order
  const avgOrderRevenue = totalOrders > 0 ? totalRevenue / totalOrders : 0;
  const avgOrderItems = totalOrders > 0 ? totalItemsSold / totalOrders : 0;
  const avgPopularity =
    menuItems.length > 0 ? totalItemsSold / menuItems.length : 0;

  // 4. Call analytics API for real calculations
  const analyticsPayload = {
    items: menuItems.map((item) => ({
      menu_name: item.menu_name,
      quantity: item.quantity,
      total_revenue: item.total_revenue,
      cogs: item.quantity > 0 ? item.cogs / item.quantity : 0, // Convert total COGS to per-unit COGS
      menu_category: item.menu_category,
    })),
  };

  const { heatmapJson, popularityJson, matrixJson, matrixDistributionJson } =
    await callAnalyticsApi(analyticsPayload);

  // 5. Create analytics record
  const analytics = await prisma.analytics.create({
    data: {
      locationId: location.id,
      sourceFile: config.analytics.sourceFile,
      periodStart: config.analytics.periodStart,
      periodEnd: config.analytics.periodEnd,
      uploadedAt: new Date(),

      // Global KPIs
      totalOrders,
      totalItemsSold,
      totalRevenue,
      totalCogs,
      totalProfit,
      totalMargin,
      avgOrderRevenue,
      avgOrderItems,
      avgPopularity,

      // Min/Max
      maxOrderItems: Math.ceil(avgOrderItems * 1.8),
      minOrderItems: Math.max(1, Math.floor(avgOrderItems * 0.4)),
      maxOrderRevenue: avgOrderRevenue * 2.5,
      minOrderRevenue: avgOrderRevenue * 0.3,

      // Analytics JSON results (from real calculations)
      matrixJson,
      matrixDistributionJson,
      heatmapJson,
      popularityJson: popularityJson || undefined,
    },
  });

  console.log(`   ✓ Created analytics record (ID: ${analytics.id})`);
  console.log(
    `      Period: ${config.analytics.periodStart.toISOString().split("T")[0]} - ${config.analytics.periodEnd.toISOString().split("T")[0]}`,
  );
  console.log(
    `      Revenue: $${totalRevenue.toFixed(0)} | Profit: $${totalProfit.toFixed(0)} | Margin: ${(totalMargin * 100).toFixed(1)}%`,
  );

  // 6. Create menu items
  for (const item of menuItems) {
    await prisma.analyticsMenuItem.create({
      data: {
        analyticsId: analytics.id,
        menuName: item.menu_name,
        quantity: item.quantity,
        totalRevenue: item.total_revenue,
        cogs: item.cogs,
        menuCategory: item.menu_category,
      },
    });
  }

  console.log(
    `   ✓ Created ${menuItems.length} menu items (all with COGS set)`,
  );

  // Calculate stats
  const highMarginItems = menuItems.filter(
    (item) => (item.total_revenue - item.cogs) / item.total_revenue > 0.6,
  );
  const lowMarginItems = menuItems.filter(
    (item) => (item.total_revenue - item.cogs) / item.total_revenue < 0.3,
  );

  console.log(`      High margin items (>60%): ${highMarginItems.length}`);
  console.log(`      Low margin items (<30%): ${lowMarginItems.length}`);
}

async function clearExistingData(locationSlug?: string): Promise<void> {
  if (locationSlug) {
    const location = await prisma.location.findUnique({
      where: { slug: locationSlug },
      include: { analytics: true },
    });

    if (location) {
      await prisma.analyticsMenuItem.deleteMany({
        where: {
          analytics: {
            locationId: location.id,
          },
        },
      });

      await prisma.analytics.deleteMany({
        where: { locationId: location.id },
      });

      console.log(`   🗑️  Cleared existing data for: ${location.name}`);
    }
  } else {
    const slugs = Object.values(SCENARIOS).map((s) => s.location.slug);
    const locations = await prisma.location.findMany({
      where: { slug: { in: slugs } },
      include: { analytics: true },
    });

    for (const location of locations) {
      await prisma.analyticsMenuItem.deleteMany({
        where: {
          analytics: {
            locationId: location.id,
          },
        },
      });

      await prisma.analytics.deleteMany({
        where: { locationId: location.id },
      });
    }

    if (locations.length > 0) {
      console.log(
        `   🗑️  Cleared existing data for ${locations.length} locations`,
      );
    }
  }
}

function listScenarios() {
  return Object.values(SCENARIOS).map((s) => ({
    id: s.id,
    name: s.name,
    description: s.description,
  }));
}

function getScenario(id: string): ScenarioConfig | null {
  return SCENARIOS[id] || null;
}

function getScenarioIds(): string[] {
  return Object.keys(SCENARIOS);
}

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  console.log("🌱 Menuyukti Scenario Seeder (v2 - Real Analytics)\n");

  // List scenarios
  if (command === "--list" || command === "-l") {
    console.log("Available scenarios:\n");
    const scenarios = listScenarios();
    scenarios.forEach((s) => {
      console.log(`  ${s.id.padEnd(25)} ${s.name}`);
      console.log(`  ${" ".repeat(25)} ${s.description}\n`);
    });
    process.exit(0);
  }

  // Seed all scenarios
  if (command === "--all" || command === "-a") {
    console.log("Seeding all scenarios...\n");
    await clearExistingData();

    const scenarioIds = getScenarioIds();
    for (const id of scenarioIds) {
      const scenario = getScenario(id);
      if (scenario) {
        await seedScenario(scenario);
      }
    }

    console.log("\n✅ All scenarios seeded successfully!");
    console.log(`   Total: ${scenarioIds.length} scenarios`);
    process.exit(0);
  }

  // Seed specific scenario
  if (command) {
    const scenario = getScenario(command);
    if (!scenario) {
      console.error(`❌ Error: Scenario "${command}" not found`);
      console.log("\nUse --list to see available scenarios");
      process.exit(1);
    }

    await clearExistingData(scenario.location.slug);
    await seedScenario(scenario);

    console.log("\n✅ Scenario seeded successfully!");
    process.exit(0);
  }

  // Interactive mode
  console.log("Usage:");
  console.log("  pnpm db:seed:v2 --list              List available scenarios");
  console.log("  pnpm db:seed:v2 --all               Seed all scenarios");
  console.log("  pnpm db:seed:v2 <scenario-id>       Seed specific scenario");
  console.log("\nExamples:");
  console.log("  pnpm db:seed:v2 thriving-cafe");
  console.log("  pnpm db:seed:v2 star-item");

  process.exit(0);
}

main()
  .catch((error) => {
    console.error("\n❌ Error seeding database:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
