from typing import List

from pydantic import BaseModel, ConfigDict, Field, model_validator

from menuyukti.indicators.models.matrix_item import MatrixCategory


# ---------------------------------------------------------
# CategoryDistribution
# ---------------------------------------------------------
# Represents ONE quadrant of the menu engineering matrix.
#
# Why this matters:
# Each category has a specific economic meaning:
#
# STAR        -> profit anchors
# PUZZLE      -> hidden margin potential
# PLOW_HORSE  -> volume drivers with weaker margin
# LOW_END     -> menu drag / clutter
#
# Agents should NEVER guess these relationships.
# The model makes them explicit.
# ---------------------------------------------------------

class CategoryDistribution(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    category: MatrixCategory = Field(description="Menu engineering quadrant.")

    item_count: int = Field(ge=0, description="Number of items in this category.")

    item_share: float = Field(
        ge=0,
        le=1,
        description="Percentage of total menu items belonging to this category.",
    )

    margin_share: float = Field(
        ge=0,
        le=1,
        description="Percentage of total contribution margin generated by this category.",
    )


# ---------------------------------------------------------
# MatrixDistribution
# ---------------------------------------------------------
# Represents the STRUCTURAL ECONOMIC STATE of the menu.
#
# This is NOT just analytics.
# This object answers questions like:
#
# - Is the business overly dependent on stars?
# - Is the menu bloated?
# - Is profit diversified?
#
# Think of this as:
#     "Portfolio Health for Restaurants"
#
# Future agents that benefit heavily from this:
#
# Promotion agents
# Risk agents
# Executive briefing agents
# Menu optimization agents
#
# Treat this model as STRATEGIC infrastructure.
# ---------------------------------------------------------


class MatrixDistribution(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    categories: List[CategoryDistribution] = Field(min_length=1)

    # Optional but HIGHLY recommended:
    # attach a timestamp or reporting period later
    # to enable trend detection.

    @model_validator(mode="after")
    def validate_and_normalize(self) -> "MatrixDistribution":
        seen: set[str] = set()
        duplicates: list[str] = []
        for category in self.categories:
            if category.category in seen:
                duplicates.append(category.category)
            seen.add(category.category)

        if duplicates:
            duplicate_values = ", ".join(sorted(set(duplicates)))
            raise ValueError(
                f"CORE_MODEL_DUPLICATE_CATEGORY_DISTRIBUTION: {duplicate_values}"
            )

        # Deterministic order for stable serialization and downstream comparisons.
        object.__setattr__(
            self,
            "categories",
            sorted(self.categories, key=lambda category: category.category),
        )
        return self
