from pydantic import BaseModel, Field
from typing import List, Literal


# ---------------------------------------------------------
# CategoryDistribution
# ---------------------------------------------------------
# Represents ONE quadrant of the menu engineering matrix.
#
# Why this matters:
# Each category has a specific economic meaning:
#
# STAR        -> profit anchors
# PUZZLE      -> hidden margin potential
# PLOW_HORSE  -> volume drivers with weaker margin
# LOW_END     -> menu drag / clutter
#
# Agents should NEVER guess these relationships.
# The model makes them explicit.
# ---------------------------------------------------------

MenuCategory = Literal["star", "puzzle", "plow_horse", "low_end"]


class CategoryDistribution(BaseModel):
    category: MenuCategory = Field(description="Menu engineering quadrant.")

    item_count: int = Field(ge=0, description="Number of items in this category.")

    item_share: float = Field(
        ge=0,
        le=1,
        description="Percentage of total menu items belonging to this category.",
    )

    margin_share: float = Field(
        ge=0,
        le=1,
        description="Percentage of total contribution margin generated by this category.",
    )


# ---------------------------------------------------------
# MatrixDistribution
# ---------------------------------------------------------
# Represents the STRUCTURAL ECONOMIC STATE of the menu.
#
# This is NOT just analytics.
# This object answers questions like:
#
# - Is the business overly dependent on stars?
# - Is the menu bloated?
# - Is profit diversified?
#
# Think of this as:
#     "Portfolio Health for Restaurants"
#
# Future agents that benefit heavily from this:
#
# Promotion agents
# Risk agents
# Executive briefing agents
# Menu optimization agents
#
# Treat this model as STRATEGIC infrastructure.
# ---------------------------------------------------------


class MatrixDistribution(BaseModel):
    categories: List[CategoryDistribution]

    # Optional but HIGHLY recommended:
    # attach a timestamp or reporting period later
    # to enable trend detection.
