from pydantic import BaseModel, ConfigDict, Field


class StructuralPrimitives(BaseModel):
    model_config = ConfigDict(frozen=True)

    """
    Represents the economic architecture of the menu.

    These metrics operate at the portfolio level.
    """

    star_margin_share: float = Field(
        ge=0,
        le=1,
        description="""
        Portion of total profit generated by star items.

        WHY IT MATTERS:
        High dependency increases financial risk.
        """,
    )

    profit_concentration: float = Field(
        ge=0,
        le=1,
        description="""
        Degree to which profit relies on a small set of items.

        WHY IT MATTERS:
        Concentrated portfolios are fragile.
        """,
    )

    low_end_share: float = Field(
        ge=0,
        le=1,
        description="""
        Percentage of menu items classified as low performers.

        WHY IT MATTERS:
        High values signal menu bloat.
        """,
    )

    diversification_score: float = Field(
        ge=0,
        le=1,
        description="""
        Evenness of profit distribution.

        WHY IT MATTERS:
        Diversified menus are more resilient.
        """,
    )

    puzzle_profit_share: float = Field(
        ge=0,
        le=1,
        description="""
        Portion of total profit generated by puzzle items.

        WHY IT MATTERS:
        Indicates upside if puzzles are promoted well.
        """,
    )

    structural_health: float = Field(
        ge=0,
        le=1,
        description="""
        Composite health score for the menu structure.

        WHY IT MATTERS:
        Provides a simple portfolio-level summary.
        """,
    )
